### ISSUE TITLE
On browser reload claimable XP isn't showing correctly

### ISSUE THREAD

**Issue by andreachapman** [tahowallet/dapp#650] opened 2023-11-07 15:22 UTC
Testing on https://xp-testing--taho-development.netlify.app/ and trying some non-happy path scenarios. This is one I tried:

1. Connected wallet for account '0x50f5f766db5b6ce04f4eacede11e1bf96d6d986e'
2. Can see that there are 6 XP to claim
3. Click to claim the first drop but then reject it and leave the modal
4. Reload the page and check the realm again and it shows 0
5. Disconnect and reconnect and now the 6 shows again

Video: https://drive.google.com/file/d/11L4Yl6hrf6YTI_wHt01PtX_wM3PvP9-K/view?usp=sharing

It seems like if you reject but then come back, those 6 XP should still have shown without having to disconnect/reconnect the wallet. It's worth nothing that if you don't refresh then it does still show the 6 XP and you can go through the claim flow again. So this seems very much like an edge case to me.

**Comment by jagodarybacka** [comment] 2023-11-08 14:43
I can't reproduce it with other accounts that have XP there right now. Looking at the video and knowing how it is working I'm 99% sure that the request asking for unclaimed XP just didn't had enough time to resolve and update the UI, sometimes I see that on the xp-testing env it takes up to 5s to load the xp data 😞 This request is not cached in any way so when the web page is reloaded we are starting with clear state and it shouldn't matter if the transaction was rejected. Unless you are able to reproduce it every time so we can sync and debug I think we can close it.

**Closed** 2023-11-09 15:10 UTC
